// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenantSolution.Data;

#nullable disable

namespace MultiTenantSolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiTenantSolution.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Santos",
                            tenantId = "tenant-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Silva",
                            tenantId = "tenant-1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carlos Oliveira",
                            tenantId = "tenant-2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "José Carvalho",
                            tenantId = "tenant-2"
                        });
                });

            modelBuilder.Entity("MultiTenantSolution.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop",
                            Name = "Laptop Dell XPS 15",
                            tenantId = "tenant-1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ergonomic wireless mouse",
                            Name = "Mouse Logitech MX Master",
                            tenantId = "tenant-1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Premium quality polo shirt",
                            Name = "Camiseta Polo Premium",
                            tenantId = "tenant-2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comfortable sports shoes",
                            Name = "Tênis Esportivo Nike",
                            tenantId = "tenant-2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
